---
abstract: 'Web server to notify GitHub Webhooks to L<App::Ikachan>'
author:
  - 'moznion <moznion@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Hash::MultiValue: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.1, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-GitHubWebhooks2Ikachan
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  App::GitHubWebhooks2Ikachan:
    file: lib/App/GitHubWebhooks2Ikachan.pm
    version: 0.03
  App::GitHubWebhooks2Ikachan::Events:
    file: lib/App/GitHubWebhooks2Ikachan/Events.pm
  App::GitHubWebhooks2Ikachan::Events::IssueComment:
    file: lib/App/GitHubWebhooks2Ikachan/Events/IssueComment.pm
  App::GitHubWebhooks2Ikachan::Events::Issues:
    file: lib/App/GitHubWebhooks2Ikachan/Events/Issues.pm
  App::GitHubWebhooks2Ikachan::Events::PullRequest:
    file: lib/App/GitHubWebhooks2Ikachan/Events/PullRequest.pm
  App::GitHubWebhooks2Ikachan::Events::Push:
    file: lib/App/GitHubWebhooks2Ikachan/Events/Push.pm
requires:
  Class::Accessor::Lite: 0
  Encode: 0
  Getopt::Long: 2.42
  JSON: 0
  LWP::UserAgent: 0
  Log::Minimal: 0
  Plack: 0
  Pod::Usage: 0
  String::IRC: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/moznion/App-GitHubWebhooks2Ikachan/issues
  homepage: https://github.com/moznion/App-GitHubWebhooks2Ikachan
  repository: git://github.com/moznion/App-GitHubWebhooks2Ikachan.git
version: 0.03
